name: Build documentation and pack
on:
  workflow_dispatch:
  push:
    branches: [ main, developing ]
  pull_request:
    branches: [ main, developing ]
  release:
    types: [published]
jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force

      - name: get pico-sdk
        run: |
          git submodule update --init
          pushd pico-sdk
          git submodule update --init
          popd

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.13.2
          packchk-version: 1.3.96
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output

      - name: Upload named artifact
        uses: actions/upload-artifact@v4
        with:
          name: RP2xxx_DFP
          path: ./output/*.pack
          if-no-files-found: error

      - name: Attach pdsc to release assets
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file_glob: true
          file: ./build/*.pdsc
          tag: ${{ github.ref }}
          overwrite: true
